
[auto_oof]
	auto_oof_on_nightmare = true
	auto_oof_on_400_uberstreak = false
	custom_auto_oof = false
	auto_oof_on_hermit = false
	auto_oof_on_moon = false
	auto_oof_on_overdrive = false
	auto_oof_on_highlander = false
	auto_oof_on_500_uberstreak = false

	[auto_oof.auto_oof]
		"§1auto_oof_on_nightmare" = true
		"§dauto_oof_on_§5corrupted§d_uberstreak" = false
		"§bauto_oof_on_moon" = false
		"§cauto_oof_on_overdrive" = false
		"§6auto_oof_on_highlander" = false
		"§dauto_oof_on_400_uberstreak" = true
		"§dauto_oof_on_500_uberstreak" = false
		"§9auto_oof_on_hermit" = false
		"§ccustom_auto_oof" = true

[general]

	[general.sounds]
		remove_player_damage_sounds_in_middle = true
		guild_message_sound = true
		custom_passive_sound = "mob.ghast.death"
		remove_gamble_sounds_in_middle = true
		"§amegastreak_sounds" = false
		guild_passive_sound = true
		"§aremove_perun_sounds_in_middle" = true
		"§aremove_player_damage_sounds_in_middle" = true
		"§aremove_stun_sounds_in_middle" = true
		"§2custom_passive_pitch" = "1.5"
		remove_stun_sounds_in_middle = true
		"§aremove_billionaire_sounds_in_middle" = true
		megastreak_sounds = false
		fish_alert = true
		remove_executioner_sounds_in_middle = false
		remove_billionaire_sounds_in_middle = true
		"§aremove_gamble_sounds_in_middle" = true
		"§aremove_executioner_sounds_in_middle" = true
		"§2guild_passive_sound" = true
		"§2custom_passive_sound" = "mob.endermen.hit"
		"§aremove_bow_sounds_in_middle" = true
		custom_passive_pitch = "1.5"
		remove_bow_sounds_in_middle = true
		"§2guild_message_sound" = false
		"§afish_alert" = true
		remove_perun_sounds_in_middle = true

	[general.dev]
		custon_action_bar = true
		"§cauto_ls_swap" = true
		auto_ls_swap = true
		low_health_threshold = 8
		"§clow_health_threshold" = 8
		auto_quick_maths = true

	[general."!general_info"]
		toggle_simple_hud = true
		"§eenable_simple_hud" = true
		toggle_major_and_minor_events = true
		"§eshow_major_and_minor_events" = true
		toggle_hud = true
		"§etoggle_hud" = true
		"§etoggle_major_and_minor_events" = true
		"§etoggle_simple_hud" = true
		"§egeneral_info" = true

	[general.display]
		pre_alert = true
		"§bcooldown_info" = true
		"§bbooster_info" = true
		"§bfree_shot_display" = true
		"§btarget_info" = false
		"§bupgrades_info" = true
		target_info = true
		egg_effect_display = true
		"§bpre_alert" = true
		"§bplayer_info" = true
		"§begg_effect_display" = true
		"§bcombat_log" = false

	[general.general_info]
		toggle_simple_hud = true
		toggle_major_and_minor_events = true
		toggle_hud = true
		"§etoggle_hud" = true
		"§etoggle_major_and_minor_events" = true
		"§etoggle_simple_hud" = true

	[general.messages]
		prestige_auto_gg = false
		rngesus_messages = false
		only_personal_bounty_claims = true
		"§ehide_stash_messages" = true
		toggle_blitz_queue_messages = true
		"§drngesus_messages" = false
		"§6hide_bounty_bumps" = true
		eradicate_blitz = false
		bounty_bumps = false
		"§6only_personal_bounty_claims" = true
		"§6bounty_bumps" = false

	[general.quality_of_life]
		stop_rendering_entities_in_spawn_when_outside = true
		mid_radius_amount = 9
		"§8hide_low_/pays" = true
		remove_particles_in_middle = true
		"§8auto-leave_party" = true
		show_ping_in_experience_bar = true
		pre_oof = false
		toggle_low_health_indicator = false
		"minimum_/pay_amount" = 5000
		"§6hide_bot_nametags" = true
		"§6lower_render_distance_in_middle" = false
		"§cmid_radius_amount" = 10
		"§8anti_cf" = false
		anti_cf = true
		lower_render_distance_in_middle = false
		"beacon_&_divine_alert" = true
		"§clow_health_indicator" = false
		"§bshow_ping_in_experience_bar" = true
		"§ctoggle_low_health_indicator" = false
		"§bping_in_experience_bar" = true
		"§6remove_particles_in_middle" = false
		"§bbeacon_&_divine_alert" = true
		"hide_low_/pays" = true
		"§cpre_oof" = false
		"§8minimum_/pay_amount" = 5000
		"§6stop_rendering_entities_in_spawn_when_outside" = true
		hide_bot_nametags = true

[dev]

	[dev.dev]
		"§cauto_ls_swap" = true
		"§clow_health_threshold" = 8

	[dev."quick_maths_/_unscramble"]
		"§eauto_unscramble" = true
		"§asay_answer_in_guild_chat" = false
		"§dauto_quick_maths" = true
		"§asay_answer_if_afk" = true

	[dev.auto_ls]
		"§cauto_ls_swap" = true
		"§clow_health_threshold" = 10

[customization]
	custom_guild_messages = true
	hud_group_colors = "&3"
	hud_colors = "&b"
	auto_chat_color = "&6"

	[customization.hud]
		"§ehud_§cc§6o§el§9o§5r" = "&b"
		"§ehud_group_§cc§6o§el§9o§5r" = "&3"

	[customization.chat]
		"§2custom_guild_messages" = true
		"§erandom_chat_§cc§6o§el§9o§5r" = true
		"§eauto_chat_§cc§6o§el§9o§5r" = ""

[vanilla_hud_hiding]
	toggle_armor_bar_display = false
	toggle_boss_bar_display = true
	toggle_hunger_bar_display = false
	toggle_xp_bar_display = true

	[vanilla_hud_hiding.render]
		"§bhide_xp_bar_display" = false
		"§btoggle_xp_bar_display" = true
		"§bhide_hunger_bar_display" = true
		"§bhide_armor_bar_display" = true
		"§btoggle_boss_bar_display" = false
		"§btoggle_armor_bar_display" = false
		"§btoggle_hunger_bar_display" = false
		"§bhide_boss_bar_display" = true

["!general"]
	rngesus_messages = false
	stop_rendering_entities_in_spawn_when_outside = false
	remove_player_damage_sounds_in_middle = true
	guild_message_sound = true
	custom_passive_sound = "mob.ghast.death"
	guild_passive_sound = true
	mid_radius_amount = 9
	remove_particles_in_middle = true
	toggle_simple_hud = true
	show_ping_in_experience_bar = true
	pre_oof = false
	toggle_major_and_minor_events = true
	egg_effect_display = true
	toggle_low_health_indicator = false
	megastreak_sounds = false
	"minimum_/pay_amount" = 5000
	toggle_blitz_queue_messages = true
	auto_ls_swap = true
	eradicate_blitz = false
	bounty_bumps = false
	fish_alert = true
	remove_billionaire_sounds_in_middle = true
	anti_cf = true
	target_info = true
	lower_render_distance_in_middle = false
	"beacon_&_divine_alert" = true
	only_personal_bounty_claims = true
	custom_passive_pitch = "3"
	prestige_auto_gg = false
	pre_alert = true
	"hide_low_/pays" = true
	toggle_hud = true
	low_health_threshold = 12
	hide_bot_nametags = true
	auto_quick_maths = true

	["!general".hud]
		toggle_hud = true

["?customization"]
	custom_guild_messages = true
	hud_group_colors = "&3"
	hud_colors = "&b"
	auto_chat_color = "&6"

