
[auto_oof]
	auto_oof_on_nightmare = true
	auto_oof_on_400_uberstreak = false
	custom_auto_oof = false
	auto_oof_on_hermit = false
	auto_oof_on_moon = false
	auto_oof_on_overdrive = false
	auto_oof_on_highlander = false

[vanilla_hud_hiding]
	toggle_armor_bar_display = false
	toggle_boss_bar_display = true
	toggle_hunger_bar_display = false
	toggle_xp_bar_display = true

["!general"]
	rngesus_messages = false
	stop_rendering_entities_in_spawn_when_outside = true
	remove_player_damage_sounds_in_middle = true
	guild_message_sound = false
	custom_passive_sound = "mob.endermen.hit"
	client_brand = ""
	guild_passive_sound = true
	mid_radius_amount = 9
	remove_particles_in_middle = false
	show_ping_in_experience_bar = true
	pre_oof = true
	toggle_major_and_minor_events = true
	egg_effect_display = true
	toggle_low_health_indicator = false
	megastreak_sounds = false
	"minimum_/pay_amount" = 5001
	toggle_blitz_queue_messages = true
	eradicate_blitz = false
	bounty_bumps = false
	fish_alert = true
	auto_ls_swap = true
	remove_billionaire_sounds_in_middle = true
	anti_cf = true
	target_info = true
	lower_render_distance_in_middle = true
	"beacon_&_divine_alert" = true
	only_personal_bounty_claims = true
	auto_chat_color = "&6"
	"swap_mid_check_(for_kings)" = true
	custom_passive_pitch = "1.5"
	prestige_auto_gg = true
	pre_alert = true
	"hide_low_/pays" = true
	toggle_hud = true
	low_health_threshold = 10
	hide_bot_nametags = true
	auto_quick_maths = true

["?customization"]
	custom_guild_messages = true
	hud_group_colors = "&3"
	hud_colors = "&b"

