
[auto_oof]
	auto_oof_on_nightmare = true
	auto_oof_on_400_uberstreak = false
	custom_auto_oof = false
	auto_oof_on_hermit = false
	auto_oof_on_moon = false
	auto_oof_on_overdrive = false
	auto_oof_on_highlander = false

[vanilla_hud_hiding]
	toggle_armor_bar_display = false
	toggle_boss_bar_display = true
	toggle_hunger_bar_display = false
	toggle_xp_bar_display = true

["!general"]
	rngesus_messages = false
	stop_rendering_entities_in_spawn_when_outside = true
	remove_player_damage_sounds_in_middle = true
	"auto_/bal_fetch" = false
	client_brand = ""
	custom_passive_sound = "mob.endermen.hit"
	guild_passive_sound = true
	mid_radius_amount = 15
	remove_particles_in_middle = false
	show_ping_in_experience_bar = true
	pre_oof = true
	egg_effect_display = true
	toggle_low_health_indicator = false
	hud_group_colors = "&3"
	toggle_major_and_minor_events = true
	megastreak_sounds = false
	"minimum_/pay_amount" = 5000
	toggle_blitz_queue_messages = true
	auto_ls_swap = true
	eradicate_blitz = true
	bounty_bumps = false
	fish_alert = true
	remove_billionaire_sounds_in_middle = true
	inventory_text_color = "0, 230, 230"
	anti_cf = true
	color_picker = "255,0,0,255"
	target_info = true
	lower_render_distance_in_middle = true
	"beacon_&_divine_alert" = true
	only_personal_bounty_claims = true
	auto_chat_color = "&3"
	custom_passive_pitch = "1.5"
	pre_alert = true
	prestige_auto_gg = true
	inventory_text = "&4&o&nPowie best WW"
	"hide_low_/pays" = true
	hud_colors = "&b"
	toggle_hud = true
	low_health_threshold = 10
	hide_bot_nametags = true

["?customization"]
	inventory_text = "&4&n&oPowie Best WW"
	hud_group_colors = "&3"
	hud_colors = "&b"

